sudo: required
services: 
  - docker 

before_install:
  - docker build -t ltreasure22/docker-react-play -f Dockerfile.dev .

script:
  - docker run ltreasure22/docker-react-play npm run test -- --coverage 